### ISSUE TITLE
Are you still working on this project?

### ISSUE THREAD

**Issue by lemin9538** [vvy/wshell#2]
Recently, I try to improve my coding skill, and write a small os kernel. I found your shell code on github, and use you shell code to my OS . Are you stilling working on Wshell development ?

**Comment by vvy** [comment]
There may be small fixes in future, but it's just a sinple sample, I don't want to make it more complicated.

**Comment by guokesong** [comment]
there is a bug     if you input  commond  "ls -al"  then "cd ",  it will be core dump

**Comment by vvy** [comment]
@guokesong fixed it. Actually any `cd` without parameter will be core dump.
